### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by makerimages** [makerimages/OSZin#34]
There are a lot of things that need to be done for this and I am really confused and kinda stuck... Paging...

Basic needs....: 
- [ ] malloc - returns a virtual address. (size-based ?)
- [ ] free - frees a virtual address
- [ ] a way to get the physical address (how?)
- [ ] A way to map the rest of the memory

**Comment by Vild** [comment]
You also need to be able to split unused memory chunks and be able to join two unused chunks together

**Comment by makerimages** [comment]
Is there `any` reading available for this, @Vild ?

**Comment by Vild** [comment]
JamesM tutorial or https://github.com/Vild/PowerNex/blob/master/powernex/src/mem/heap.c  else Idk

**Comment by makerimages** [comment]
JamesM's stuff is kinda generally known to not be too great.. I guess it's a way to learn, though.

**Comment by Vild** [comment]
Like they say at the osdev wiki. It's a good start if you take everything with a pinch of salt.

**Comment by makerimages** [comment]
It would appear that by implementing @Vild's code pretty much as-is, we have hereby achieved paging!
