### ISSUE TITLE
PIT timer

### ISSUE THREAD

**Issue by makerimages** [makerimages/OSZin#7]
Need a timer to do timing stuff (Such as a thread scheduler).

**Comment by makerimages** [comment]
Researching, will work on over the next weekend or two.

**Comment by ghost** [comment]
Unfortunately, I couldn't build all the files with strange errors — you definitely have incorrect Makefile. Also, you're declaring functions/routines with the same name in [IDT.cpp](https://github.com/makerimages/OSZin/blob/master/src/OSZin/modules/IDT.cpp) and [interrupt-entry.s](https://github.com/makerimages/OSZin/blob/master/src/OSZin/asm/interrupt-entry.s). Finally, you don't need to have a semicolon after function declaration: [IDT.cpp#L108](https://github.com/makerimages/OSZin/blob/master/src/OSZin/modules/IDT.cpp#L108).

**Comment by makerimages** [comment]
- What errors? And what are you building with?
- Will have a look at the names
- Those are there god knows why.

**Comment by ghost** [comment]
@makerimages, actually, your code has only one error, others were because of the Makefile I wrote yesterday was wrong.

```
src/libc/string/uitoa.cpp: In function 'char* uitoa(unsigned int, char*, int)':
src/libc/string/uitoa.cpp:15:16: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
     if ( value < 0 && base == 10 )
                ^
```

Another Makefile that I wrote today is at https://gist.github.com/ExeTwezz/7847b621fc9e52e3a8f0.

**Comment by makerimages** [comment]
Hmm, I've got that as a warning :D

**Comment by ghost** [comment]
@makerimages, that's because I added `-Werror` to `CFLAGS` in the Makefile I referenced to before.

**Comment by makerimages** [comment]
@exetwezz Going home today, will try out ASAP.

**Comment by ghost** [comment]
@makerimages, I'll be online until 18:00 GMT today, so I think I just won't have time to help you to figure out what's the problem (currently I'm reading the ARM Architecture Reference Manual). But I'm going to stay online at night (21:00 GMT) between Saturday and Sunday.

**Comment by makerimages** [comment]
@exetwezz Well, the Makefile works.  Now to solve the PIT...
